// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace heracles.webapp.client
{
    using System.Threading;
    using System.Threading.Tasks;

    /// <summary>
    /// Extension methods for HeraclesClient.
    /// </summary>
    public static partial class HeraclesClientExtensions
    {
            /// <summary>
            /// Returns the money in Heracles format
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='input'>
            /// </param>
            public static string FormatMoney(this IHeraclesClient operations, string input)
            {
                return operations.FormatMoneyAsync(input).GetAwaiter().GetResult();
            }

            /// <summary>
            /// Returns the money in Heracles format
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='input'>
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<string> FormatMoneyAsync(this IHeraclesClient operations, string input, CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.FormatMoneyWithHttpMessagesAsync(input, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

    }
}
