name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up .NET Core 3.1
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x' # SDK Version to use; x will use the latest version of the 3.1 channel

    - name: Install dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Run Console Unit Tests
      run: dotnet test test/heracles.unit.tests/heracles.unit.tests.csproj --no-build

    - name: Run WebApp Unit Tests
      run: dotnet test test/heracles.webapp.unit.tests/heracles.webapp.unit.tests.csproj --no-build

    - name: Stryker.NET install
      run: dotnet tool install -g dotnet-stryker
    
    - name: Run Mutation Testing on Console Unit Tests
      run: |
        cd test/heracles.unit.tests
        dotnet stryker

    - name: Upload Striker HTML Report for Console
      uses: actions/upload-artifact@v2
      with:
        name: stryker-report-console
        path: test/heracles.unit.tests/StrykerOutput/**/reports/mutation-report.html

    - name: Build the tagged Docker image
      run: docker build . --file src/heracles.webapp/Dockerfile

    - name: Run Heracles as docker container
      run: docker run -t -d --name heracles -p 32786:80 heracles

    - name: Run Integration Tests
      env: 
        BASEURI: http://localhost:32786
      run: dotnet test test/heracles.webapp.integration.tests/heracles.webapp.integration.tests.csproj --no-build