on:
  push:
    tags:
      - 'v*'

name: Create Release

jobs:
  build:
    name: Create Release
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
        - os: ubuntu-latest
          TARGET: linux-x64
          NAME: linux
          FULLNAME: Linux
        - os: windows-latest
          TARGET: win10-x64
          NAME: win
          FULLNAME: Windows
        - os: macos-latest
          TARGET: ost-x64
          NAME: mac
          FULLNAME: MacOS

    runs-on: ${{ matrix.os }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Publish binary
        run: dotnet publish -c Release -r ${{matrix.TARGET}} -o heracles-${{matrix.NAME}}
      
      - name: Zip binaries
        if: matrix.os != 'windows-latest'
        run: zip -r ./heracles-${{matrix.NAME}}.zip ./heracles-${{matrix.NAME}}/*
        
      - name: Zip windows binaries
        if: matrix.os == 'windows-latest'
        uses: montudor/action-zip@v0.1.0
        with:
          args: zip -qq -r ./heracles-win.zip ./heracles-win/*

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}-${{matrix.NAME}}
          release_name: Release ${{ github.ref }} ${{matrix.FULLNAME}}    
          draft: false
          prerelease: false

      - name: Upload binary zip to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./heracles-${{matrix.NAME}}.zip
          asset_name: heracles-${{matrix.NAME}}.zip
          asset_content_type: application/zip